language: node_js
node_js: '12'
dist: xenial
# When pushing a tagged commit, Travis adds two builds: one with the tag, one
# without. We only want to build the one with the tag, because it's the one
# that runs the deployment stage
if: '!(commit_message =~ /^Release/ && tag is blank)'
jobs:
  include:
    # Test on Windows/Mac/Linux using latest Node.js.
    # Also test on Linux with older Node.js versions.
    # We do not run each possible combination to make CI faster.
    - os: windows
    - os: osx
    - node_js: '8.12.0'
    - node_js: '12'
    # Test coverage check must happen after tests for the whole matrix have
    # been performed, so we get the merged coverage map
    - stage: Coverage check
      # If this fails during a PR, CI will fail. However when CI fails, codecov
      # does not post any comment. Since codecov comments are nicer than
      # Travis Buddy comments for this, we skip it during PRs. Also this makes
      # PRs checks faster.
      if: type != pull_request
      script: gulp coverage
    # Deployment must happen after tests for the whole matrix have been
    # performed, so we use `jobs.include` with a different `stage`.
    - stage: Deploy
      if: type != pull_request && tag is not blank
      script: gulp publish
      # NPM_TOKEN environment variable
      env:
        secure: 'L1L5X8nPZQfIDnIQriwyEY813jin9gq5RqVdxqVNK5YEKas9M8lSTvHDHoE/zeAvmtSygAQX7HljfpFnpmhh3cDARcr6LdZkEwQNiA/clDiB/jknAYtAqp0PJNKPyK+OYv+/uQQcsSWvWSNfjPiC7vyp1x38pQJqNpIoJkFIXfw4+zRmN2rUUn5WpxXE+nLDs7QZsty1Q427iy0Zn7gi1sK+amTGl5fhqlrOL1ak43ysMQbBLTkBJsVm7dvyfSAk8bWNitxj0jITQjwM3YHbWqqJKdvl4sx2UA/wbXDqmcYW7POx7g25HwMZMYJXjUdmk0da5iby2N+c1aSmo4M3DvjklGzoNKRze2RiSRKImpzsB0SYvj1vQldZDF81Gza2ZZIYrR/OA01WQjqo88ZOnyCD7FyNTkFr/LBsI+QbPsg4xFnLL5iCSy1V0d0vKgTsNE2BDDgslPQYFpf/CHrYtcXesI6P9VDhJdbAurniDIcwgTZtQMi0YecRT6Zp/X+q1GTtoEHT3KB7JJCocye59lKBlueZZGD8hpfWOmNZZy+0MpiyD/4gU7UkDAv/ZD5lLMVgVKGiGjhsY2X9cXKt0itBKOBLS8l4jpEO8Rsq9z6zH3jlGCmak+ZX8rDo2pLHkSGuDBju0xAO2C/B7Q8757KhQ4ZWtsn9y4R8pSKMY9E='
notifications:
  webhooks:
    - https://www.travisbuddy.com?only=failed,errored&insertMode=update
  email: false
# We do not use `cache: npm` because downloading and uploading the cache
# actually takes more time than it saves during `npm ci`.
